import express from 'express';
import * as wieChatController from '../controllers/wiechat.controller.js';
import { authenticateToken } from '../middleware/auth.middleware.js';
const router = express.Router();
router.use(authenticateToken);
router.get('/suggestions', wieChatController.getWieChatSuggestions);
router.get('/search', wieChatController.searchWieUsersForChat);
router.post('/create', wieChatController.createOrGetWieChat);
router.get('/list', wieChatController.getWieUserChats);
router.get('/requests', wieChatController.getMessageRequests); 
router.get('/unread-count', wieChatController.getUnreadMessageCount);
router.post('/send', wieChatController.sendWieMessage);
router.get('/:chatId/get-chat-details', wieChatController.getChatDetails);
router.post('/:chatId/mark-read', wieChatController.markWieMessagesAsRead);
router.post('/:chatId/mark-unread', wieChatController.markWieMessagesAsUnread);
router.get('/:chatId/messages', wieChatController.getWieChatMessages);
router.get('/user/:userId/status', wieChatController.getUserOnlineStatus); 
router.post('/:chatId/accept', wieChatController.acceptMessageRequest);
router.post('/:chatId/decline', wieChatController.declineMessageRequest);
router.delete('/:chatId/clear', wieChatController.clearWieChatMessages);
router.delete('/:chatId/messages/:messageId', wieChatController.deleteWieMessage);
router.post('/:chatId/messages/delete-for-me', wieChatController.deleteMessagesForMe);
router.post('/:chatId/messages/delete-for-everyone', wieChatController.deleteMessagesForEveryone); 
router.delete('/:chatId', wieChatController.deleteWieChat);
router.get('/:chatId/messages/selection', wieChatController.getMessagesForSelection);
router.delete('/:chatId/delete-for-me', wieChatController.deleteChatForMe);
router.get('/unread-users-count', wieChatController.getUnreadUsersCount);
export default router;
