const eventCategories = {
  "Arts, Culture, & Literature": [
    "Art Exhibitions","Cultural Festivals","Theater Performances","Literature Festivals","Historical Reenactments","Art Installations","Art Workshops & Competitions","Guided Art Walks","Printmaking & Conceptual Art","Residency Showcases","Art Auctions","Poetry Readings","Book Launch Events","Author Meet & Greets","Storytelling Sessions","Film Screenings","Short Film Festivals","Heritage Walks","Museum Tours","Craft Fairs","Handicraft Exhibitions","Photography Exhibitions","Sculpture Exhibitions","Calligraphy Workshops","Creative Writing Workshops","Drama Workshops","Open Mic Poetry Nights","Comic Cons","Zine Fairs","Cultural Parades","Traditional Dance Performances","Folk Art Festivals","Literary Debates","Panel Discussions","Cultural Conferences"
  ],
  Music: [
    "Concerts","Music Festivals","Live Performances","Battle of the Bands","DJ Nights","Karaoke Nights","Open Mics & Jam Sessions","Acoustic Nights","Album Launch Events","Music Tours","Symphony Orchestra Performances","Opera Shows","Choir Performances","Tribute Shows","Music Competitions","Band Nights","Indie Music Shows","Rap Battles","Electronic Dance Music (EDM) Events","Classical Music Concerts","Folk Music Events","Cultural Music Nights","Music Workshops","Music Masterclasses","Instrumental Recitals","Music Award Shows","Street Music Performances","Unplugged Sessions","Live Recording Sessions"
  ],
  "Entertainment & Performing Arts": [
    "Comedy Shows","Magic Shows","Circus Performances","Stand up Comedy","Improv Shows","Drama Plays","Musical Theatre","Dance Performances","Ballet Shows","Street Performances","Puppet Shows","Mime Acts","Talent Shows","Reality Show Auditions","Award Ceremonies","Live Game Shows","Variety Shows","Flash Mob","Stunt Shows","Illusion Shows","Drag Shows","Burlesque Shows","Carnival Performances","Theme Park Shows","Interactive Theatre","Monologue Performances","Storytelling Performances","Cultural Stage Shows","Broadway style Productions"
  ],
  Dance: [
    "Recitals & Showcases","Competitions & Galas","Social Dance","Dance Workshops","Themed Dances","Classical Dance","Contemporary Dance","Street & Urban Dance","Bollywood & Tollywood Dance","Folk & Traditional Dance","K-pop Dance","Ballet Performances","Hip-Hop Battles","Salsa & Bachata Nights","Zumba Sessions","Dance Marathons","Flash Mob","Dance Reality Show Auditions","Choreography Showcases","Intercollegiate Dance Fests","Couples Dance Competitions","Freestyle Dance Battles","Latin Dance Festivals","Ballroom Dance Competitions","Breakdance","Dance Fitness Events","Garba & Dandiya Nights","Fusion Dance Shows","Dance Retreats","International Dance Festivals","Dance Film Screenings"
  ],
  "Sports, Fitness, & Adventure": [
    "Sporting Competitions","Marathons & Races","Fitness Workshops","Adventure Sports","Camping & Hiking","Turf Booking","Wrestling","Esports","Cycling Events","Triathlons","Swimming Meets","Football","Cricket","Badminton","Basketball","Volleyball Matches","Table Tennis","Kabaddi","Athletics Meets","Gymnastics Competitions","Bodybuilding Championships","CrossFit Competitions","Yoga Retreats","Meditation Camps","Rock Climbing Events","Trekking Expeditions","Mountain Biking","Surfing Competitions","Skateboarding Events","Self-Defense Workshops","Martial Arts Tournaments","Boxing Matches","MMA Fights","Car & Bike Rallies","Motorsport Racing","Obstacle Course Races","Adventure Bootcamps","Outdoor Survival Camps","Fishing Tournaments","Horse Riding"
  ],
  "Motorsport Racing": [
    "Formula Racing","Stock Car Racing","Touring Car Championships","Motorcycle Grand Prix","Superbike Racing","Motocross Events","Mud racing","Endurance Racing","Drag Racing","Street Circuit Racing","Rally Racing","Rallycross Events","Karting Championships","Go-Kart Races","Drift Competitions","Time Attack Events","Hill Climb Races","Off-Road Racing","Desert Rally","Autocross Events","Track Day Events","Time Trial Races","Electric Vehicle Racing","Vintage Car Racing","Truck Racing","Speedway Racing","Ice Racing","Demolition Derby","Burnout Competitions","Motorsport Exhibitions","Custom Car Shows","Auto Expos","Motorcycle Stunt Shows","Supercar Meetups","4x4 Off-Road Challenges","ATV Racing","Jet Ski Racing","Boat Racing","Drone Racing League Events","Sim Racing Tournaments"
  ],
  "Education & Learning": [
    "Workshop","Seminar","Technological learning","Conferences & Summits","Academic Competitions & MUNs","Career Fairs & Counseling","Public Lectures","Bootcamps","Certification Programs","College Fests","Webinars","Startup Competitions","Quiz Sessions","Hackathons","Coding Competitions","Research Paper Presentations","Science Fairs","Robotics Competitions","Debate Competitions","Group Discussions","Language Learning Sessions","Skill Development Programs","Teacher Training Programs","Leadership Workshops","Entrepreneurship Workshops","Industry Networking Events","Internship Drives","Educational Expos","Study Abroad Fairs","Alumni Meetups","Innovation Challenges","Case Study Competitions","Design Thinking Workshops","Data Science Workshops","AI & ML Bootcamps","Financial Literacy Workshops","Exam Preparation Sessions","Scholarship Awareness Programs"
  ],
  "Business & Innovation": [
    "Tech Expos","Hackathons","Product Launches","Robotics Competitions","Startup Events","Trade Shows","Networking Events","Business Conferences","Entrepreneurship Summits","Investor Pitch Nights","Venture Capital Meetups","Angel Investor Forums","Industry Panel Discussions","Corporate Meetups","B2B Meetings","B2C Expos","Innovation Showcases","Startup Demo Days","Incubator & Accelerator Programs","Business Workshops","Leadership Summits","Marketing Conferences","Sales Bootcamps","E-commerce Expos","FinTech Conferences","AI & Tech Conferences","Blockchain Summits","SaaS Conferences","Manufacturing Expos","Franchise Exhibitions","Business Award Ceremonies","Corporate Training Programs","Strategic Planning Workshops","Business Networking Breakfasts","Women in Business Events","Young Entrepreneur Meetups"
  ],
  "Food, Lifestyle, & Wellness": [
    "Food Festivals","Wine Tastings","Cooking Classes","Yoga & Spiritual Retreats","Mindfulness Workshops","Fashion Shows","Street Food Carnivals","Baking Workshops","Barista Workshops","Cocktail Making Classes","Beer Festivals","Organic Food Markets","Farmers Markets","Vegan & Plant-Based Expos","Health & Wellness Expos","Meditation Sessions","Sound Healing Sessions","Ayurveda Workshops","Nutrition Seminars","Diet & Weight Loss Programs","Fitness Retreats","Spa & Detox Retreats","Beauty & Skincare Workshops","Makeup Masterclasses","Personal Styling Sessions","Sustainable Living Workshops","Zero-Waste Lifestyle Events","Home & Living Expos","Interior Design Exhibitions","Pet Wellness Events","Holistic Healing Fairs","Self-Care Workshops","Mental Health Awareness Events","Tea & Coffee Festivals","Luxury Lifestyle Exhibitions"
  ],
  "Film, Media, & Gaming": [
    "Film Festivals & Screenings","Animation Showcases","Board Game Nights","Cosplay Conventions","Movie Premieres","Short Film Competitions","Documentary Screenings","Film Festivals","Web Series Launches","Fan Meetups","Celebrity Meet & Greets","Comic Cons","Gaming Tournaments","Esports Championships","LAN Parties","Game Launch Events","Game Development Conferences","VR & AR Experience Events","Streaming & Content Creator Meetups","Podcast Live Shows","Photography Exhibitions","Media & Journalism Conferences","Film Making Workshops","Script Writing Workshops","Dubbing & Voice Acting Workshops","Trailer Launch Events","Red Carpet Events","Movie Marathons","Retro Film Nights","Arcade Gaming Events","Tabletop RPG Sessions","Speedrunning Competitions","Digital Art Showcases"
  ],
  "Travel, Holidays, & Tourism": [
    "Travel Expos","Destination Showcases","Cruise Events","Holiday Events","Adventure Travel Meetups","Backpacking Workshops","Travel Photography Tours","Cultural Exchange Programs","Visa & Immigration Seminars","Study Abroad Tours","Luxury Travel Exhibitions","Road Trip Rallies","Van Life Gatherings","Eco-Tourism Conferences","Wildlife Safari Trips","Heritage Walks","City Tours & Guided Walks","Island Hopping Tours","Mountain Expedition Trips","Beach Festivals","Travel Blogger Meetups","Travel Storytelling Sessions","Pilgrimage Tours","Spiritual Travel Retreats","Ski Trips & Snow Tours","Desert Camping Experiences","International Tourism Fairs","Travel Deal Fairs","Staycation Events","Theme Park Tours","Culinary Tourism Tours","Festival Tourism Packages","Volunteer Travel Programs","Cultural Immersion Camps","Photography Expeditions"
  ],
  "Festivals & Celebrations": [
    "National & Regional Festivals","Harvest Festivals","Lantern Festivals","Cultural Parades","Religious Festivals","Music & Arts Festivals","Food & Drink Festivals","Film Festivals","Flower Festivals","Winter Festivals","Summer Festivals","Spring Festivals","Autumn Festivals","Street Festivals","Carnivals","Fireworks Festivals","Light & Sound Shows","Heritage Festivals","Folk Festivals","Tribal Festivals","Boat Festivals","Desert Festivals","Beach Festivals","Cultural Heritage Days","Community Fairs","Anniversary Celebrations","Foundation Day Celebrations","Independence Day Celebrations","New Year Celebrations","Themed Costume Festivals","International Cultural Festivals","Charity Festivals","Art & Craft Festivals","Literary Festivals","Spiritual Gatherings"
  ],
  "Environment, Sustainability, & Agriculture": [
    "Eco Festivals","Sustainable Living Workshops","Tree-Planting & Clean Energy Campaigns","Agricultural Fairs & Farmers' Markets","Green Hackathons","Cyclothons","Eco-Tourism Trails","Green Tech Conferences","Climate Action Summits","Organic Farming Workshops","Permaculture Training Programs","Water Conservation Drives","Beach Clean Up Campaigns","River Restoration Projects","Wildlife Conservation Camps","Biodiversity Awareness Programs","Urban Gardening Workshops","Composting Workshops","Zero-Waste Events","Sustainable Fashion Shows","Renewable Energy Expos","Solar & Wind Energy Workshops","Environmental Film Screenings","Nature Walks & Bird Watching Tours","Sustainable Architecture Expos","Carbon Footprint Awareness Campaigns","Green Startup Pitch Events","Eco Innovation Challenges","Community Recycling Drives","Plastic-Free Campaigns","Soil Health Awareness Programs","Agri Tech Exhibitions","Hydroponics & Aquaponics Workshops","Seed Exchange Fairs","Farm to Table Events"
  ],
  "Religious & Spiritual Events": [
    "Pilgrimages","Spiritual Retreats","Meditation Camps","Prayer Meetings","Bhajan & Kirtan Nights","Satsang Gatherings","Religious Discourses","Scripture Study Sessions","Interfaith Dialogues","Spiritual Workshops","Healing & Blessing Sessions","Temple Festivals","Church Conventions","Mosque Gatherings","Ashram Retreats","Silent Retreats","Chanting Sessions","Spiritual Conferences","Youth Spiritual Camps","Faith Based Charity Events","Religious Processions","Holy Day Celebrations","Spiritual Counseling Sessions","Energy Healing Workshops","Yoga & Philosophy Sessions","Vedic Ritual Ceremonies","Baptism Ceremonies","Ramadan Iftar Gatherings","Gospel Music Nights","Community Prayer Breakfasts"
  ],
  "Night Life": [
    "Clubbing","Themed Parties","Karaoke Nights","DJ Nights","Pubbing","Rave Parties","After Parties","Ladies' Night","Gentlemen's Night","Neon Glow Parties","Retro Nights","Bollywood Nights","EDM Nights","Hip Hop Nights","Latin Dance Nights","Salsa Nights","Beach Parties","Pool Parties","Rooftop Parties","Live Band Nights","Open Mic Nights","Stand up Comedy Nights","Drag Nights","Silent Disco","Masquerade Balls","Casino Nights","Cocktail Nights","Wine & Dine Nights","Pub Crawls","Bar Hopping Events","Midnight Movie Screenings","Game & Trivia Nights","Foam Parties","Full Moon Parties","Singles Mixers"
  ],
  Other: ["Other"],
};
export default eventCategories;
