import express from 'express';
import { index,getCountries,signupSendOtp,signupVerifyOtp,login,resendOtp,getProfile,updateProfile,googleAuth,googleCallback  } from '../services/wie-user.service';
import { authenticateToken } from '../middlewares/auth.middleware';
const router: express.Router = express.Router();
router.get('/', index);
router.get('/countries', getCountries);
router.post('/signup/send-otp', signupSendOtp);
router.post('/signup/verify-otp', signupVerifyOtp);
router.post('/login', login);
router.post('/resend-otp', resendOtp);
router.get('/google/auth', googleAuth);
router.get('/google/callback', googleCallback);
router.get('/get-profile', authenticateToken, getProfile);
router.put('/update-profile', authenticateToken, updateProfile);
export default router;
