import express from 'express';
import { index,getCountries,signupSendOtp,signupVerifyOtp,login,logout,resendOtp,getProfile,updateProfile,googleAuth,googleCallback,getMicrosoftAuthUrl,getAppleAuthUrl,forgotPassword,verifyResetOTP,resetPassword,getUserLocation,updateUserLocation, checkCanSetPassword,setPasswordForGoogleUser,changePassword,searchUsers,getUserById,getSuggestedUsers,updateHeartbeat,
    getAccountPrivacy,updateAccountPrivacy,muteUser,unmuteUser,getMutedUsers,getMutedCount,checkMuteStatus
  } from '../services/wie-user.service';
import { authenticateToken } from '../middlewares/auth.middleware';
import upload from '../middlewares/upload';
const router: express.Router = express.Router();
router.get('/', index);
router.get('/countries', getCountries);
router.post('/signup/send-otp', signupSendOtp);
router.post('/signup/verify-otp', signupVerifyOtp);
router.post('/login', login);
router.post('/logout', authenticateToken, logout);
router.post('/resend-otp', resendOtp);
router.get('/check-can-set-password', authenticateToken, checkCanSetPassword);
router.post('/set-password-for-google-user', authenticateToken, setPasswordForGoogleUser);
router.post('/change-password', authenticateToken, changePassword);
router.get('/google/auth', googleAuth);
router.get('/google/callback', googleCallback);
router.get('/microsoft-auth', getMicrosoftAuthUrl);
router.get('/apple-auth', getAppleAuthUrl);
router.get('/get-profile', authenticateToken, getProfile);
router.put('/update-profile', authenticateToken,upload.single('profile_picture'), updateProfile);
router.post('/forgot-password', forgotPassword);
router.post('/verify-reset-otp', verifyResetOTP);
router.post('/reset-password', resetPassword);
router.get('/get-location', authenticateToken, getUserLocation);
router.put('/update-location', authenticateToken, updateUserLocation);
router.get('/search', authenticateToken, searchUsers);
router.get('/suggested', authenticateToken, getSuggestedUsers);
router.get('/:userId', authenticateToken, getUserById);
router.post('/heartbeat', authenticateToken, updateHeartbeat);
router.get('/account-privacy', authenticateToken, getAccountPrivacy);
router.put('/account-privacy', authenticateToken, updateAccountPrivacy);
router.post('/mute', authenticateToken, muteUser);
router.post('/unmute', authenticateToken, unmuteUser);
router.get('/mutes', authenticateToken, getMutedUsers);
router.get('/muted-count', authenticateToken, getMutedCount);
export default router;
