import express from 'express';
import * as followController from '../controllers/follow.controller';
import * as followService from '../services/follow.service';
import { authenticateToken } from '../middleware/auth.middleware';
const router: express.Router = express.Router();
router.use(authenticateToken);
router.post('/follow/:targetUserId', followController.followUser);
router.delete('/unfollow/:targetUserId', followController.unfollowUser);
router.get('/followers/:userId', followController.getFollowers);
router.get('/following/:userId', followController.getFollowing);
router.get('/other-followers/:userId', followController.getOtherFollowers);
router.get('/other-following/:userId', followController.getOtherFollowing);
router.get('/follow/status/:targetUserId', followController.checkFollowStatus);
router.get('/follow/stats/:userId', followController.getFollowStats);
router.get('/is-following/:targetUserId', followController.checkIsFollowing);
router.get('/follow-requests', followController.getFollowRequests);
router.post('/accept-request/:followerId', followController.acceptFollowRequest);
router.post('/reject-request/:followerId', followController.rejectFollowRequest);
router.delete('/cancel-request/:targetUserId', followController.cancelFollowRequest);
router.get('/detailed-status/:targetUserId', followController.getDetailedFollowStatus);
router.get('/follow-request/status/:fromUserId', followController.checkFollowRequestStatus);
router.get('/get-send-follow-request/:userId', followController.getSentFollowRequests);
router.post('/auto-accept-requests', followController.autoAcceptPendingRequests);
router.get('/is-followed-by/:targetUserId', followController.checkIsFollowedBy);
export default router;
