import express from 'express';
import { uploadFields, uploadTicketMedia } from '../middlewares/upload.js'; 
import multer from 'multer';
import { uploadGroupFiles } from '../middlewares/upload.js';
import {getUserData,CreateGroup, UpdateGroup,createTicketBasicInfo, getGroups, getUserGroupCapabilities,updateTicketMedia,updateTicketAddOns,updateTicketDetails,updateTicketTerms,submitTicket,getAllGroupTicketId,
getTicketById,deleteTicket,deleteSubEvent,deleteEventPermenently,deleteAllEvents,viewTickets, getAllDeletedEvents,getDeletedEventById,recoverDeletedEvent,getAllGroups,getAllLiveEvents,recoverSubEvent} from '../services/ticket.service.js';
import { getGroupsTypes,updateSubEvent,getTicketSubEvents,getGroupView,getGroupById,getOtherGroupView,getMyEvents,getMyEventById,getMyLiveEvents,getMyLiveEventView,getMyPastEvents,getMyUpcomingEvents,getMyPreviousEventView,getOthersEvents,getOthersEventsById,getOtherLiveEvents,
getOthersPastEvents,getGroupStatistics,confirmEvent,goLiveEvent,getAddOnEventLiveView,getPreviousEvents,showEventBankDetails,showAllBankDetails,LiveEventBankDetails,likeEvent,unlikeEvent,checkUserLiked,groupEventCount,totalEventsCreatedCount,makeEventCompleted,getPostalDetailsFromCoords,
getPreviousEventView,getPreviousSubEventView,getPreviousEventStatistics,getPreviousEventMonthlyStats,getPreviousSubEventMonthlyStats,getPreviousEventCapacityStats,getPreviousSubEventCapacityStats,getEventMetrics,getEventStatsByDate, getEventGrowthStats, getEventMonthlyChart,
cancelEvent, getCancellationReport, rehostEvent, rehostSubEvent,goLiveSubEvent,getAuditHistory,getEventVersions,getSubEventAudit, getEventFinancialSummaryHandler, getEventTransactionListHandler } from '../controller/ticket.controller.js';
import { protect } from '../middlewares/auth.js';
const router = express.Router();
router.use(protect);
router.get('/get-user-data',getUserData);
router.post('/create-group',uploadGroupFiles, CreateGroup);
router.put('/update-group/:groupId', protect, uploadGroupFiles, UpdateGroup);
router.get('/get-groups', getGroups);
router.post('/create-event/:groupId', createTicketBasicInfo);
router.post('/create-event/:groupId/:ticketId', createTicketBasicInfo);
router.get('/user-group-capabilities', getUserGroupCapabilities);
router.post('/update-ticket-media/:ticketId', updateTicketMedia);
router.post('/ticket-addons/:ticketId',uploadTicketMedia, updateTicketAddOns);
router.put('/update-sub-event/:ticketId/:subEventId',uploadTicketMedia, updateSubEvent);
router.post('/update-ticket-details/:ticketId', updateTicketDetails);
router.post('/ticket-terms/:ticketId', updateTicketTerms);
router.post('/submit-ticket/:ticketId', submitTicket);
router.get('/get-all-tickets', getAllGroupTicketId);
router.get('/get-ticket-sub-events/:ticketId', getTicketSubEvents);
router.get('/get-ticket/:ticketId', getTicketById);
router.post('/delete-ticket/:ticketId', deleteTicket);
router.post('/delete-sub-event/:ticketId/:subEventId', protect, deleteSubEvent);
router.delete('/delete-event-permanently/:ticketId', protect, deleteEventPermenently);
router.post('/delete-all-events',protect, deleteAllEvents);
router.get('/get-all-deleted-events', getAllDeletedEvents);
router.get('/get-deleted-event/:eventId', protect, getDeletedEventById);
router.put('/recover-deleted-event/:ticketId',protect, recoverDeletedEvent);
router.get('/view-tickets', viewTickets);
router.get('/get-groups-types', getGroupsTypes);
router.get('/get-group-view/:ticketId', getGroupView);
router.get('/get-group-by-id/:groupId', getGroupById);
router.get('/get-other-group-view/:ticketId', getOtherGroupView);
router.get('/my-events', getMyEvents);
router.get('/my-event-view/:ticketId', getMyEventById);
router.get('/my-live-events', getMyLiveEvents);
router.get('/my-live-event-view/:ticketId', getMyLiveEventView);
router.get('/addon-event-live-view/:subEventId', getAddOnEventLiveView);
router.get('/my-past-events', getMyPastEvents);
router.get('/my-upcoming-events', getMyUpcomingEvents);
router.get('/my-previous-event-view/:ticketId', getMyPreviousEventView);
router.get('/get-others-events/:otherId',getOthersEvents);
router.get('/get-other-ticket-id/:otherId/:ticketId',getOthersEventsById)
router.get('/get-others-live-events/:otherId',getOtherLiveEvents);
router.get('/get-others-past-events/:otherId',getOthersPastEvents);
router.get('/get-group-statistics', getGroupStatistics);
router.post('/confirm-event/:ticketId',confirmEvent);
router.post('/go-live-event/:ticketId',goLiveEvent);
router.get('/get-previous-events',protect, getPreviousEvents);
router.post('/make-event-completed', makeEventCompleted);
router.get('/show-event-bank-details',protect, showEventBankDetails);
router.get('/show-all-bank-details',protect, showAllBankDetails);
router.get('/live-event-bank-details',protect, LiveEventBankDetails);
router.post('/like-event/:ticketId',protect, likeEvent);
router.post('/unlike-event/:ticketId',unlikeEvent);
router.get('/check-user-liked/:ticketId',checkUserLiked);
router.get('/group-event-count',protect, groupEventCount);
router.get('/total-events-created-count',protect, totalEventsCreatedCount);
router.get('/get-postal-details', getPostalDetailsFromCoords);
router.get('/get-all-live-events',getAllLiveEvents);
router.get('/get-all-groups', getAllGroups);
router.get('/previous-event-statistics/:ticketId', getPreviousEventStatistics);
router.get('/previous-event-view/:ticketId', getPreviousEventView);
router.get('/previous-sub-event-view/:subEventId', getPreviousSubEventView);
router.get('/previous-event-monthly-stats/:ticketId', getPreviousEventMonthlyStats);
router.get('/previous-sub-event-monthly-stats/:subEventId', getPreviousSubEventMonthlyStats);
router.get('/previous-event-capacity-stats/:ticketId', getPreviousEventCapacityStats);
router.get('/previous-sub-event-capacity-stats/:subEventId', getPreviousSubEventCapacityStats);
router.get('/event-metrics/:ticketId', getEventMetrics);
router.get('/event-stats-by-date/:ticketId', protect, getEventStatsByDate);
router.get('/event-growth-stats/:ticketId', protect, getEventGrowthStats);
router.get('/event-monthly-chart/:ticketId', protect, getEventMonthlyChart);
router.post('/cancel-event/:ticketId', cancelEvent);
router.post('/:ticketId/sub-events/:subEventId/cancel', cancelEvent);
router.get('/get-cancellation-report/:ticketId', getCancellationReport);
router.get('/get-cancellation-report/:ticketId/sub-event/:subEventId', getCancellationReport);
router.post('/rehost-event/:ticketId', rehostEvent);
router.post('/:parentTicketId/sub-events/:subEventId/rehost', rehostSubEvent);
router.post('/:parentTicketId/sub-events/:subEventId/go-live', goLiveSubEvent);
router.post('/:parentTicketId/sub-events/:subEventId/recover', protect, recoverSubEvent);
router.get('/audit-history/:ticketId', getAuditHistory);
router.get('/event-versions/:originalEventId', getEventVersions);
router.get('/audit/sub-event/:parentEventId/:subEventId', getSubEventAudit);
router.get('/event-financial-summary/:ticketId',getEventFinancialSummaryHandler);
router.get('/event-transactions/:ticketId',getEventTransactionListHandler);
export default router;
