import express from 'express';
import { uploadFields, uploadTicketMedia } from '../middlewares/upload.js'; 
import multer from 'multer';
import {getUserData,CreateGroup, createTicketBasicInfo, getGroups, getUserGroupCapabilities,updateTicketMedia,updateTicketAddOns,updateTicketDetails,updateTicketTerms,submitTicket,getAllGroupTicketId,
getTicketById,deleteTicket,deleteSubEvent,viewTickets, getAllDeletedEvents} from '../services/ticket.service.js';
import { getGroupsTypes,updateSubEvent,getTicketSubEvents,getGroupView,getOtherGroupView,getMyEvents,getMyEventById,getMyLiveEvents,getMyLiveEventView,getMyPastEvents,getMyUpcomingEvents,getMyPreviousEventView,getOthersEvents,getOthersEventsById,getOtherLiveEvents,
getOthersPastEvents,getGroupStatistics,confirmEvent,goLiveEvent,getPreviousEvents,showEventBankDetails,showAllBankDetails,LiveEventBankDetails,likeEvent,unlikeEvent,checkUserLiked,groupEventCount,totalEventsCreatedCount,makeEventCompleted } from '../controller/ticket.controller.js';
import { protect } from '../middlewares/auth.js';
const router = express.Router();
router.use(protect);
router.get('/get-user-data',getUserData);
router.post('/create-group', CreateGroup);
router.get('/get-groups', getGroups);
router.post('/create-event/:groupId', createTicketBasicInfo);
router.post('/create-event/:groupId/:ticketId', createTicketBasicInfo);
router.get('/user-group-capabilities', getUserGroupCapabilities);
router.post('/update-ticket-media/:ticketId', updateTicketMedia);
router.post('/ticket-addons/:ticketId',uploadTicketMedia, updateTicketAddOns);
router.put('/update-sub-event/:ticketId/:subEventId',uploadTicketMedia, updateSubEvent);
router.post('/update-ticket-details/:ticketId', updateTicketDetails);
router.post('/ticket-terms/:ticketId', updateTicketTerms);
router.post('/submit-ticket/:ticketId', submitTicket);
router.get('/get-all-tickets', getAllGroupTicketId);
router.get('/get-ticket-sub-events/:ticketId', getTicketSubEvents);
router.get('/get-ticket/:ticketId', getTicketById);
router.post('/delete-ticket/:ticketId', deleteTicket);
router.post('/delete-sub-event/:ticketId/:subEventId', deleteSubEvent);
router.get('/get-all-deleted-events', getAllDeletedEvents);
router.get('/view-tickets', viewTickets);
router.get('/get-groups-types', getGroupsTypes);
router.get('/get-group-view/:ticketId', getGroupView);
router.get('/get-other-group-view/:ticketId', getOtherGroupView);
router.get('/my-events', getMyEvents);
router.get('/my-event-view/:ticketId', getMyEventById);
router.get('/my-live-events', getMyLiveEvents);
router.get('/my-live-event-view/:ticketId', getMyLiveEventView);
router.get('/my-past-events', getMyPastEvents);
router.get('/my-upcoming-events', getMyUpcomingEvents);
router.get('/my-previous-event-view/:ticketId', getMyPreviousEventView);
router.get('/get-others-events/:otherId',getOthersEvents);
router.get('/get-other-ticket-id/:otherId/:ticketId',getOthersEventsById)
router.get('/get-others-live-events/:otherId',getOtherLiveEvents);
router.get('/get-others-past-events/:otherId',getOthersPastEvents);
router.get('/get-group-statistics', getGroupStatistics);
router.post('/confirm-event/:ticketId',confirmEvent);
router.post('/go-live-event/:ticketId',goLiveEvent);
router.get('/get-previous-events',protect, getPreviousEvents);
router.post('/make-event-completed', makeEventCompleted);
router.get('/show-event-bank-details',protect, showEventBankDetails);
router.get('/show-all-bank-details',protect, showAllBankDetails);
router.get('/live-event-bank-details',protect, LiveEventBankDetails);
router.post('/like-event/:ticketId',protect, likeEvent);
router.post('/unlike-event/:ticketId',unlikeEvent);
router.get('/check-user-liked/:ticketId',checkUserLiked);
router.get('/group-event-count',protect, groupEventCount);
router.get('/total-events-created-count',protect, totalEventsCreatedCount);
export default router;
