import express from 'express';
import {getUserData,CreateGroup, createTicketBasicInfo, getGroups, getUserGroupCapabilities,updateTicketMedia,updateTicketAddOns,updateTicketDetails,updateTicketTerms,submitTicket,getAllGroupTicketId,
getTicketById,deleteTicket,viewTickets } from '../services/ticket.service.js';
import { getGroupsTypes,updateSubEvent,getTicketSubEvents,getGroupView,getMyEvents,getMyEventById,getMyLiveEvents,getMyLiveEventView,getMyPastEvents,getMyUpcomingEvents,getOthersEvents,getOtherLiveEvents,
getOthersPastEvents,getGroupStatistics,confirmEvent,goLiveEvent,getPreviousEvents,showEventBankDetails,likeEvent,unlikeEvent,checkUserLiked } from '../controller/ticket.controller.js';
import { protect } from '../middlewares/auth.js';
const router = express.Router();
router.use(protect);
router.get('/get-user-data',getUserData);
router.post('/create-group', CreateGroup);
router.get('/get-groups', getGroups);
router.post('/create-event/:groupId', createTicketBasicInfo);
router.post('/create-event/:groupId/:ticketId', createTicketBasicInfo);
router.get('/user-group-capabilities', getUserGroupCapabilities);
router.post('/update-ticket-media/:ticketId', updateTicketMedia);
router.post('/ticket-addons/:ticketId', updateTicketAddOns);
router.put('/update-sub-event/:ticketId/:subEventId', updateSubEvent);
router.post('/update-ticket-details/:ticketId', updateTicketDetails);
router.post('/ticket-terms/:ticketId', updateTicketTerms);
router.post('/submit-ticket/:ticketId', submitTicket);
router.get('/get-all-tickets', getAllGroupTicketId);
router.get('/get-ticket-sub-events/:ticketId', getTicketSubEvents);
router.get('/get-ticket/:ticketId', getTicketById);
router.delete('/delete-ticket/:ticketId', deleteTicket);
router.get('/view-tickets', viewTickets);
router.get('/get-groups-types', getGroupsTypes);
router.get('/get-group-view/:ticketId', getGroupView);
router.get('/my-events', getMyEvents);
router.get('/my-event-view/:ticketId', getMyEventById);
router.get('/my-live-events', getMyLiveEvents);
router.get('/my-live-event-view/:ticketId', getMyLiveEventView);
router.get('/my-past-events', getMyPastEvents);
router.get('/my-upcoming-events', getMyUpcomingEvents);
router.get('/get-others-events/:otherId',getOthersEvents);
router.get('/get-others-live-events/:otherId',getOtherLiveEvents);
router.get('/get-others-past-events/:otherId',getOthersPastEvents);
router.get('/get-group-statistics', getGroupStatistics);
router.post('/confirm-event/:ticketId',confirmEvent);
router.post('/go-live-event/:ticketId',goLiveEvent);
router.get('/get-previous-events',protect, getPreviousEvents);
router.get('/show-event-bank-details',protect, showEventBankDetails);
router.post('/like-event/:ticketId',protect, likeEvent);
router.post('/unlike-event/:ticketId',unlikeEvent);
router.get('/check-user-liked/:ticketId',checkUserLiked);
export default router;
